source:
  mqtt:
    - host: "pioreactor01.local"
      port: 1883
      username: "pioreactor"
      password: "raspberry"
      timeout: 15
      timestamp_format: "%Y-%m-%dT%H:%M:%S.%fZ"

simulation:
  filepath: "./modelLibrary/cstr_one_inlet_one_mal.h5"
  
topic_map:
    - name: "od"
      type: "nested_with_channel"
      label: "ods"
      topic_suffix: "/od_reading/ods"
      channel: "2"
      noise: 0.001
      state_index: 1
    - name: "rpm"
      type: "tuple"
      topic_suffix: "/stirring/measured_rpm"
      label: "measured_rpm"
    - name: "temp"
      topic_suffix: "temperature_automation/temperature"
      type: "tuple"
      label: "temperature"
    - name: "od2"
      topic_suffix: "od_reading/od2"
      type: "tuple"
      label: "od"

simulation:
  filepath: "./modelLibrary/cstr_one_inlet_one_mal.h5"
