source:
  mqtt:
    - host: "10.42.0.1"
      port: 1883
      username: "pioreactor"
      password: "raspberry"
      timeout: 11
    - hostname: "pioreactor02"
      port: 13
      username: "pioreactor"
      password: "raspebrry"
      timeout: 60